---
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: beta-backend

resources:
- name: terraforming
  type: git
  source:
    branch: master
    uri: git@github.com:vchrisb/pcf-automation-gcp-paving
    private_key: ((github.private_key))

- name: env-state-gcp
  type: terraform
  source:
    #storage:
      #endpoint: ((s3.endpoint))
      #use_signing_v4: true
      #region_name: ((s3.region))
      #bucket: ((s3.bucket))
      #bucket_path: ((s3.bucket_path))
      #access_key_id: ((s3.access_key_id))
      #secret_access_key: ((s3.secret_access_key))
    backend_type: s3
    backend_config:
      bucket: ((s3.bucket))
      key: terraform-ci/terraform.tfstate
      region: us-east-1
      access_key: ((s3.access_key_id))
      secret_key: ((s3.secret_access_key))
    vars:
      project: ((gcp.project))
      region: ((gcp.region))
      zones: ((gcp.zones))
      service_account_key: ((gcp.gcp_service_account))
      buckets_location: ((gcp.buckets_location))
      dns_suffix: ((pas.dns_suffix))
      ssl_cert: ((pas.ssl_cert.certificate))
      ssl_private_key: ((pas.ssl_cert.private_key))
      opsman_vm: false
      opsman_image_url: "https://storage.googleapis.com/ops-manager-us/pcf-gcp-2.3-build.224.tar.gz"

jobs:
- name: pave-gcp
  serial: true
  public: false
  plan:
  - aggregate:
    - get: terraforming
      trigger: true
  - do:
    - put: env-state-gcp
      params:
        env_name: ((pas.env_name))
        terraform_source: terraforming/terraforming-gcp/terraforming-pas
        delete_on_failure: true

- name: delete-gcp
  serial: true
  public: false
  plan:
  - aggregate:
    - get: terraforming
      trigger: false
  - do:
    - put: env-state-gcp
      params:
        terraform_source: terraforming/terraforming-gcp/terraforming-pas
        delete_on_failure: true
        env_name: ((pas.env_name))
        action: destroy
      get_params:
        action: destroy
