---
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: beta-backend

resources:
- name: terraforming
  type: git
  source:
    branch: master
    uri: git@github.com:vchrisb/pcf-automation-gcp-paving
    private_key: ((github.private_key))

- name: env-state-gcp
  type: terraform
  source:
    #storage:
      #endpoint: ((s3.endpoint))
      #use_signing_v4: true
      #region_name: ((s3.region))
      #bucket: ((s3.bucket))
      #bucket_path: ((s3.bucket_path))
      #access_key_id: ((s3.access_key_id))
      #secret_access_key: ((s3.secret_access_key))
    # backend_type: s3
    # backend_config:
    #   bucket: ((s3.bucket))
    #   key: terraform-ci/terraform.tfstate
    #   region: us-east-1
    #   access_key: ((s3.access_key_id))
    #   secret_key: ((s3.secret_access_key))
    backend_type: gcs
    backend_config:
      bucket: ((gcp.bucket))
      prefix: ((pas.env_name))/terraform/state
      credentials: ((gcp.gcp_service_account))
    vars:
      project: ((gcp.project))
      region: ((gcp.region))
      zones: ((gcp.zones))
      service_account_key: ((gcp.gcp_service_account))
      buckets_location: ((gcp.buckets_location))
      dns_suffix: ((pas.dns_suffix))
      ssl_cert: ((pas.ssl_cert.certificate))
      ssl_private_key: ((pas.ssl_cert.private_key))
      opsman_vm: false
      opsman_image_url: ""

jobs:
- name: pave-gcp
  serial: true
  public: false
  plan:
  - aggregate:
    - get: terraforming
      trigger: true
  - do:
    - put: env-state-gcp
      params:
        env_name: ((pas.env_name))
        terraform_source: terraforming/terraforming-gcp/terraforming-pas
        delete_on_failure: false
    - task: render-template
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: jess/jq}
        inputs:
          - name: env-state-gcp
        outputs:
          - name: some-files
        run:
          path: /bin/sh
          args:
            - -c
            - |
                echo '{{ index (ds "data").azs 0 }}' > some-files/input

    - task: render-config
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: hairyhenderson/gomplate
            tag: alpine
        inputs:
          - name: env-state-gcp
          - name: some-files
        outputs:
          - name: config_template
        run:
          path: /bin/sh
          args:
            - -c
            - |
                /bin/gomplate -f some-files/input -d data=file://$(pwd)/env-state-gcp/metadata?type=application/json -o config_template/test --verbose
                cat config_template/test

- name: delete-gcp
  serial: true
  public: false
  plan:
  - aggregate:
    - get: terraforming
      trigger: false
  - do:
    - put: env-state-gcp
      params:
        terraform_source: terraforming/terraforming-gcp/terraforming-pas
        delete_on_failure: true
        env_name: ((pas.env_name))
        action: destroy
      get_params:
        action: destroy
